/**
*Licensed Materials - Property of IBM
*5725-G84
*@ Copyright IBM Corp. 2000, 2016 All Rights Reserved
*US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*/

#ifndef  __lsbevents_h__
#define __lsbevents_h__

#define FIELD_ACTION_FLAGS "action_flags"
#define FIELD_ACTION_MASK "action_mask"
#define FIELD_ACTION_LOG_STATUS_CODE "action_log_status_code"
#define FIELD_ACTION_STATUS_CODE "action_status_code"
#define FIELD_ACTION_PERIOD "action_period"
#define FIELD_ACTION_PID "action_pid"
#define FIELD_ACTION_SIGNAL "action_signal"
#define FIELD_ADDITIONAL_INFO "additional_info"
#define FIELD_ADV_RSV_ID "adv_rsv_id"
#define FIELD_APP_PROFILE "app_profile"
#define FIELD_APS_STRING "aps_string"
#define FIELD_ASKED_HOSTS "asked_hosts"
#define FIELD_BEGIN_TIME "begin_time"
#define FIELD_BEGIN_TIME_UTC "begin_time_utc"
#define FIELD_CHARGED_SAAP "charged_saap"
#define FIELD_CHECKPOINT_DIR "checkpoint_dir"
#define FIELD_CHECKPOINT_INTERVAL "checkpoint_interval"
#define FIELD_CLUSTER_NAME "cluster_name"
#define FIELD_COMMAND_SPOOL "command_spool"
#define FIELD_CPU_TIME "cpu_time"
#define FIELD_CWD "cwd"
#define FIELD_DEPEND_COND "depend_cond"
#define FIELD_DST_CLUSTER_NAME "dst_cluster_name"
#define FIELD_DST_JOB_ID "dst_job_id"
#define FIELD_EFFECTIVE_RES_REQ "effective_res_req"
#define FIELD_ALLOC_SLOTS_NUM  "alloc_slots_num"
#define FIELD_END_TIME "end_time"
#define FIELD_END_TIME_UTC "end_time_utc"
#define FIELD_ERR_FILE "err_file"
/* time_t -- formatted time */
#define FIELD_EVENT_TIME "event_time"
/* UNIX time (integer or long) */
#define FIELD_EVENT_TIME_UTC "event_time_utc"
#define FIELD_EVENT_TYPE "event_type"
#define FIELD_EXCEPT_MASK "except_mask"
#define FIELD_EXCEPT_LIST "except_list"
#define FIELD_EXCEPT_CODE "exception_code"
#define FIELD_EXEC_CWD "cwd"
#define FIELD_EXEC_HOME "exec_home"
#define FIELD_EXEC_HOSTS "exec_hosts"

// added by zk on 2018-10-15
#define FIELD_JOB_EXIT_REASON "exit_reason"

// added by zk on 2017-02-14
// change the key name of nested execution host object from "exec_hosts" to "exec_hosts_list"
#define FIELD_EXEC_HOSTS_LIST "exec_hosts_list"

#define FIELD_EXECHOST_SLOT_NUM  "num_slots"
#define FIELD_EXECHOST_STIME     FIELD_RU_STIME
#define FIELD_EXECHOST_UTIME     FIELD_RU_UTIME
#define FIELD_EXECHOST_MEM_USAGE "mem_usage"
#define FIELD_EXECHOST_SWAP_USAGE "swap_usage"
#define FIELD_EXEC_RUSAGE "exec_rusage"
#define FIELD_EXEC_UID "exec_uid"
#define FIELD_EXEC_USER_NAME "exec_user_name"
#define FIELD_EXIT_INFO "exit_info"
#define FIELD_EXIT_STATUS "exit_status"
#define FIELD_EXTSCHED "extsched"
#define FIELD_FLOW_ID "flow_id"
#define FIELD_FORWARD_TIME "forward_time"
#define FIELD_HOST_CPU_FACTOR "host_cpu_factor"
#define FIELD_HOST_NAME "host_name"
#define FIELD_HOST_SPEC "host_spec"
#define FIELD_IN_FILE "in_file"
#define FIELD_IN_FILE_SPOOL "in_file_spool"
#define FIELD_JOB_ARRAY_IDX "job_arr_idx"
#define FIELD_JOB_ARRAY_IDX_LIST "job_arr_idx_list"
#define FIELD_JOB_ARRAY_IDX_RANGE_START "job_arr_idx_range_start"
#define FIELD_JOB_ARRAY_IDX_RANGE_STEP "job_arr_idx_range_step"
#define FIELD_JOB_ARRAY_IDX_RANGE_END "job_arr_idx_range_end"
#define FIELD_JOB_COMMAND "command"
#define FIELD_JOB_DESCRIPTION "job_description"
#define FIELD_JOB_EXIT_CODE "exit_code"
#define FIELD_JOB_FILE "job_file"
#define FIELD_JOB_FLAGS "job_flags"
#define FIELD_JOB_GROUP "job_group"
#define FIELD_JOB_ID "job_id"
#define FIELD_JOB_IDX_LIST "job_idx_list"
#define FIELD_JOB_NAME "job_name"
#define FIELD_JOB_NAME_FULL "job_name_full"
#define FIELD_JOB_OPTS "job_opts"
#define FIELD_JOB_OPTS_DELETE "job_opts_delete"
#define FIELD_JOB_OPTS_2 "job_opts_2"
#define FIELD_JOB_OPTS_2_DELETE "job_opts_2_delete"
#define FIELD_JOB_OPTS_3 "job_opts_3"
#define FIELD_JOB_OPTS_3_DELETE "job_opts_3_delete"
#define FIELD_JOB_PGID "job_pgid"
#define FIELD_JOB_PID "job_pid"
#define FIELD_JOB_SPOOL_DIR "job_spool_dir"
#define FIELD_JOB_STATUS_CODE "job_status_code"
#define FIELD_JOB_STATUS "job_status"
#define FIELD_JOB_TYPE "job_type"
#define FIELD_LIC_PROJECT_NAME "lic_project_name"
#define FIELD_LOGIN_SHELL "login_shell"
#define FIELD_MAIL_USER "mail_user"
#define FIELD_MAX_MEM "max_mem"
#define FIELD_MAX_SWAP "max_swap"

#define FIELD_METRIC_HOST_QUERIES "host_queries"
#define FIELD_METRIC_JOB_BUCKETS "job_buckets"
#define FIELD_METRIC_JOB_QUERIES "job_queries"
#define FIELD_METRIC_JOB_SUBMIT_REQS "job_submit_reqs"
#define FIELD_METRIC_JOBS_COMPLETED "jobs_completed"
#define FIELD_METRIC_JOBS_DISPATCHED "jobs_dispatched"
#define FIELD_METRIC_JOBS_FROM_REMOTE "jobs_from_remote"
#define FIELD_METRIC_JOBS_SUBMITTED "jobs_submitted"
#define FIELD_METRIC_JOBS_TO_REMOTE "jobs_to_remote"
#define FIELD_METRIC_LOGINTERVAL "loginterval"
#define FIELD_METRIC_LOGSTART "logstart"
#define FIELD_METRIC_MATCH_HOST_CRIT "match_host_crit"
#define FIELD_METRIC_MBD_FILES_FREE "mbd_files_free"
#define FIELD_METRIC_MBD_FILES_USED "mbd_files_used"
#define FIELD_METRIC_MBD_REQS "mbatchd_requests"
#define FIELD_METRIC_QUEUE_QUERIES "queue_queries"
#define FIELD_METRIC_SCHED_INTERVAL "sched_interval"

#define FIELD_MSG_IDX "msg_idx"
#define FIELD_NIOS_PORT "nios_port"
#define FIELD_NUM_ARR_ELEMENTS "num_arr_elements"
#define FIELD_NUM_ASKED_HOSTS "num_asked_hosts"
#define FIELD_NUM_EXEC_HOSTS "num_exec_hosts"
#define FIELD_NUM_EXEC_PROCESSORS "num_processors"
#define FIELD_NUM_PGIDS "num_pgids"
#define FIELD_NUM_PIDS "num_pids"
#define FIELD_NUM_PROCESSORS "req_num_procs_min"
#define FIELD_NUM_RESERVE_HOSTS "num_reserve_hosts"
#define FIELD_NUM_THREADS "num_threads"
#define FIELD_NUM_XFER_FILES "num_xfer_files"
#define FIELD_OUT_FILE "out_file"
#define FIELD_OUT_DIR "out_dir"
#define FIELD_PEND_REASON "pend_reason"
#define FIELD_PEND_SUBREASON "pend_subreason"
#define FIELD_PGIDS "pgids"
#define FIELD_PID_INFO "pid_info"
#define FIELD_POSITION "position"
#define FIELD_POSITION_BASE "base"
#define FIELD_POSTEXEC_CMD "postexec_cmd"
#define FIELD_PREEMPT_BACKFILL "preempt_backfill"
#define FIELD_PREEXEC_CMD "preexec_cmd"
#define FIELD_PRIORITY "prio"
#define FIELD_PROJECT_NAME "project_name"
#define FIELD_QUEUE_NAME "queue_name"
#define FIELD_QUEUE_POST_CMD "queue_post_cmd"
#define FIELD_QUEUE_PRE_CMD "queue_pre_cmd"
#define FIELD_REMOTE_CLUSTER_NAME "remote_cluster_name"
#define FIELD_REMOTE_JOB_ATTRS "remote_job_attrs"
#define FIELD_REQ_NUM_PROCS_MAX "req_num_procs_max"
#define FIELD_REQUEUE_EXIT_VALS "requeue_exit_vals"
#define FIELD_RES_REQ "res_req"
#define FIELD_RESERVE_HOSTS "reserve_hosts"
#define FIELD_RESOURCE_LIMIT "resource_limit"
#define FIELD_RESOURCE_LIMIT_CLUS "cluster_resource_limit"
#define FIELD_RESOURCE_LIMIT_JOB "job_resource_limit"
#define FIELD_RESTART_PID "restart_pid"

/* rlimit group */
#define FIELD_RLIMIT_CORE     "core"
#define FIELD_RLIMIT_CPU      "cpu"
#define FIELD_RLIMIT_DATA     "data"
#define FIELD_RLIMIT_FILES    "files"
#define FIELD_RLIMIT_FSIZE    "fsize"
#define FIELD_RLIMIT_OPEN_MAX "open_max"
#define FIELD_RLIMIT_PROCESS  "process"
#define FIELD_RLIMIT_RSS      "rss"
#define FIELD_RLIMIT_RUNTIME  "runtime"
#define FIELD_RLIMIT_STACK    "stack"
#define FIELD_RLIMIT_THREAD   "thread"
#define FIELD_RLIMIT_VMEM     "vmem"

/* rusage group */
#define FIELD_RU_BLOCK_IN  "block_in"
#define FIELD_RU_BLOCK_OUT "block_out"
#define FIELD_RU_EXUTIME   "exutime"
#define FIELD_RU_IDRSS     "idrss"
#define FIELD_RU_IO_CHARS  "io_chars"
#define FIELD_RU_ISMRSS    "ismrss"
#define FIELD_RU_ISRSS     "isrss"
#define FIELD_RU_IXRSS     "ixrss"
#define FIELD_RU_MAJOR_FAULTS     "major_faults"
#define FIELD_RU_MINOR_FAULTS     "minor_faults"
#define FIELD_RU_MAX_RSS    "max_rss"
#define FIELD_RU_MSGRCV     "msgrcv"
#define FIELD_RU_MSGSND     "msgsnd"
#define FIELD_RU_NUM_INV_CSW     "num_inv_csw"
#define FIELD_RU_NUM_SIGNALS     "num_signals"
#define FIELD_RU_NUM_SWAPOUT     "num_swapout"
#define FIELD_RU_NUM_V_CSW       "num_v_csw"
#define FIELD_RU_STIME      "stime"
#define FIELD_RU_UTIME      "utime"

#define FIELD_RUN_RU_MEM_USAGE  FIELD_EXECHOST_MEM_USAGE 
#define FIELD_RUN_RU_SWAP_USAGE FIELD_EXECHOST_SWAP_USAGE

#define FIELD_RUNLIMIT "runlimit"
#define FIELD_RUNTIME_EST "runtime_est"
#define FIELD_RUN_COUNT "run_count"
#define FIELD_RUN_OPTIONS "run_options"
#define FIELD_RUN_TIME "run_time"
#define FIELD_RUN_RUSAGE "run_rusage"
#define FIELD_RUSAGE "rusage"
#define FIELD_RUSAGE_FLAG "rusage_flag"
#define FIELD_SCHED_HOST_TYPE "sched_host_type"
#define FIELD_SEQUENCE "sequence"
#define FIELD_SIGNAL_SYMBOL "signal_symbol"
#define FIELD_SIGNAL_VALUE "signal_value"
#define FIELD_SLA "sla"
#define FIELD_SLA_RUN_LIMIT "sla_run_limit"
#define FIELD_SLA_SCALED_RUN_LIMIT "sla_scaled_run_limit"
#define FIELD_SRC_CLUSTER_NAME "src_cluster_name"
#define FIELD_SRC_JOB_ID "src_job_id"
#define FIELD_START_TIME "start_time"
#define FIELD_START_TIME_UTC "start_time_utc"
#define FIELD_SUBMISSION_CLUSTER_NAME "src_cluster_name"
#define FIELD_SUBMISSION_HOST_NAME "submission_host_name"
#define FIELD_SUBMIT_TIME "submit_time"
#define FIELD_SUBMIT_TIME_UTC "submit_time_utc"
#define FIELD_SUBMITTER_HOME "submitter_home"
#define FIELD_TERM_TIME "term_time"
#define FIELD_TERM_TIME_UTC "term_time_utc"
#define FIELD_TIME_EVENT "time_event"
#define FIELD_TOTAL_PROVISION_TIME "total_provision_time"
#define FIELD_TURNAROUND_TIME "turnaround_time"
#define FIELD_PEND_TIME "pend_time"
#define FIELD_HOG_FACTOR "hog_factor"
#define FIELD_EXPAND_FACTOR "expand_factor"
#define FIELD_EXIT_FLAG "exit_flag"
#define FIELD_DONE_FLAG "done_flag"
#define FIELD_UID "uid"
#define FIELD_UMASK "umask"
#define FIELD_USER_GROUP_NAME "user_group_name"
#define FIELD_USER_NAME "user_name"
#define FIELD_VERSION "version"
#define FIELD_VIRTUALIZATION "virtualization"
#define FIELD_WARNING_ACTION "warning_action"
#define FIELD_WARNING_TIME_PERIOD "warning_time_period"
#define FIELD_XFER_FILES "xfer_files"

#define FIELD_NOT_SWITCHED "not_switched"
#define FIELD_SIG "sig"
#define FIELD_SIG_1 "sig1"
#define FIELD_SIG_1_FLAGS "sig1_flags"
#define FIELD_NOT_MODIFIED "not_modified"
#define FIELD_MISC_OPTS_4_PEND_SIG  "misc_opts_4_pend_sig"
#define FIELD_EXIT_REASON "exit_reason"
#define FIELD_CLUSTER_RLIMIT "cluster_rlimit"
#define FIELD_JOB_RLIMIT "job_rlimit"
#define FIELD_FILE_NAME "file_name"
#define FIELD_DATA_STATUS "data_status"
#define FIELD_DATA_SIZE "data_size"
#define FIELD_MSG_INDEX "msg_idx"
#define FIELD_DESC "desc"
#define FIELD_MEMB_SIZE "memb_size"
#define FIELD_MEMB_JOB_ID "memb_job_id"
#define FIELD_PERFORMANCE_METRIC "performance_metrics"
#define FIELD_SAMPLE_INTERVAL "sample_interval"
#define FIELD_NUM_JOBS "num_jobs"
#define FIELD_RUNTIME_DELTA "runtime_delta"
#define FIELD_REMOTE_ATT "job_rmt_attr"
#define FIELD_PROVTIME_DELTA "provtime_delta"
#define FIELD_SLOT_FLAG "slot_flag"


#endif /* __lsbevents_h__ */
